# Generated by Django 5.1.7 on 2025-03-16 21:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('date_of_hit', models.DateField()),
                ('time_of_hit', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SmoothPursuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_lag', models.FloatField()),
                ('mean_squared_error', models.FloatField()),
                ('pearson_coefficient', models.FloatField()),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Plr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_pupil_diam', models.FloatField()),
                ('min_pupil_diam', models.FloatField()),
                ('percent_contstriction', models.FloatField()),
                ('peak_constriction_velocity', models.FloatField()),
                ('average_constriction_velocity', models.FloatField()),
                ('peak_dilation_velocity', models.FloatField()),
                ('average_dilation_velocity', models.FloatField()),
                ('time_to_redilation', models.FloatField()),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
