# Generated by Django 5.1.7 on 2025-03-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('date_of_hit', models.DateTimeField()),
                ('time_of_hit', models.TimeField()),
            ],
        ),
    ]
