# Generated by Django 5.1.7 on 2025-03-20 02:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('date_of_hit', models.DateField()),
                ('time_of_hit', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SmoothPursuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_lag_l_180', models.FloatField()),
                ('mean_squared_error_l_180', models.FloatField()),
                ('pearson_coefficient_l_180', models.FloatField()),
                ('phase_lag_r_180', models.FloatField()),
                ('mean_squared_error_r_180', models.FloatField()),
                ('pearson_coefficient_r_180', models.FloatField()),
                ('phase_lag_l_360', models.FloatField()),
                ('mean_squared_error_l_360', models.FloatField()),
                ('pearson_coefficient_l_360', models.FloatField()),
                ('phase_lag_r_360', models.FloatField()),
                ('mean_squared_error_r_360', models.FloatField()),
                ('pearson_coefficient_r_360', models.FloatField()),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smooth_pursuit', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Plr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_pupil_diam_l', models.FloatField()),
                ('min_pupil_diam_l', models.FloatField()),
                ('percent_contstriction_l', models.FloatField()),
                ('peak_constriction_velocity_l', models.FloatField()),
                ('average_constriction_velocity_l', models.FloatField()),
                ('peak_dilation_velocity_l', models.FloatField()),
                ('average_dilation_velocity_l', models.FloatField()),
                ('time_to_redilation_l', models.FloatField()),
                ('max_pupil_diam_r', models.FloatField()),
                ('min_pupil_diam_r', models.FloatField()),
                ('percent_contstriction_r', models.FloatField()),
                ('peak_constriction_velocity_r', models.FloatField()),
                ('average_constriction_velocity_r', models.FloatField()),
                ('peak_dilation_velocity_r', models.FloatField()),
                ('average_dilation_velocity_r', models.FloatField()),
                ('time_to_redilation_r', models.FloatField()),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plr', to='api.user')),
            ],
        ),
    ]
