# Generated by Django 5.1.7 on 2025-03-16 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at_alter_user_date_of_hit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_pupil_diam', models.FloatField()),
                ('min_pupil_diam', models.FloatField()),
                ('percent_contstriction', models.FloatField()),
                ('peak_constriction_velocity', models.FloatField()),
                ('average_constriction_velocity', models.FloatField()),
                ('peak_dilation_velocity', models.FloatField()),
                ('average_dilation_velocity', models.FloatField()),
                ('time_to_redilation', models.FloatField()),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SmoothPursuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_lag', models.FloatField()),
                ('mean_squared_error', models.FloatField()),
                ('pearson_coefficient', models.FloatField()),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
